### ISSUE TITLE
accessToken

### ISSUE THREAD

**Issue by raggabrashtrout** [MrWh1teR0se/OnlyFansDL#1]
Hi
I've tried getting grabbing the accessToken from the  Developer-Console > Console / F12  both Chrome and FireFox both return NULL
Yes I've logged in

![image](https://user-images.githubusercontent.com/14979539/118300573-fd916800-b4d9-11eb-9ab0-6c975c5050a7.png)

Run this in console 

`for (var a in localStorage) {
   console.log(a, ' = ', localStorage[a]);
}`
Returns the following
![image](https://user-images.githubusercontent.com/14979539/118302662-6548b280-b4dc-11eb-85d3-35db29916a38.png)

**Comment by MrWh1teR0se** [comment]
OnlyFans has changed a few things and this downloader no longer supports downloading as it used to.
